version: 2.1
jobs:

  build-python3:
    docker:
      - image: ocrd/core-cuda-tf1
    environment:
      PIP: pip3
      PYTHON: python3
    steps:
      - checkout
      - run: make deps
      - run: make install
      - run: make build
  
  test-python3:
    docker:
      # for the CI we need ocrd-tesserocr-recognize
      # (it is easier to install nvidia-tensorflow than build Tesseract)
      - image: ocrd/tesserocr
    environment:
      PIP: pip3
      PYTHON: python3
    steps:
      - run: apt-get update && apt-get install -y --no-install-recommends make wget
      - checkout
      - run: make -C /build/core deps-cuda deps-tf1
      - run: make deps
      - run: make install
      - run: make deps-test
      # restore trained model from previous run
      # (change name of the key here when model ABI changes)
      - restore_cache:
          key: v0.3-model_dta_test
      # test with the (cached) test model
      - run: make test TEST_TRAINING=1 |& tee test.log
      # test with the prebuilt DTA model
      - run: make test |& tee -a test.log
      - store_artifacts:
          path: test.log
      # store trained model for next run
      # (change name of the key here when model ABI changes)
      - save_cache:
          key: v0.3-model_dta_test
          paths:
            - model_dta_test.h5
    # The resource_class feature allows configuring CPU and RAM resources for each job. Different resource classes are available for different executors. https://circleci.com/docs/2.0/configuration-reference/#resourceclass
    resource_class: large

  deploy-docker:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout
      - setup_remote_docker: # https://circleci.com/docs/2.0/building-docker-images/
          docker_layer_caching: true
      - run: make docker
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKERHUB_PASS" | docker login --username "$DOCKERHUB_USER" --password-stdin
      - run: docker push ocrd/keraslm

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-python3
      - test-python3
  deploy:
    jobs:
      - deploy-docker:
          filters:
            branches:
              only: master
