version: 2.1
jobs:

  build-python3:
    docker:
      - image: ocrd/core
    environment:
      PIP: pip3
      PYTHON: python3
    steps:
      - run: apt-get update && apt-get install -y --no-install-recommends make git
      - checkout
      - run: make deps
      - run: make install
  test-python3:
    docker:
      - image: ocrd/tesserocr
    environment:
      PIP: pip3
      PYTHON: python3
    steps:
      - run: apt-get update && apt-get install -y --no-install-recommends make git sed wget unzip xsltproc
      - checkout
      - run: make deps
      - run: make install
      - run: make deps-test
      - run: make test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-python3
      - test-python3
